"use client";
import './globals.css'; 
import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillFacebook, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Typed from "typed.js";
import { FaTelegram } from "react-icons/fa";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import photo1 from "../public/1.png";
import photo2 from "../public/2.png";
import photo3 from "../public/3.png";
import photo4 from "../public/4.png";
import photo5 from "../public/5.png";
import photo6 from "../public/6.png";
import photo7 from "../public/7.png";
import photo8 from "../public/8.png";
import photo9 from "../public/9.png";
import photo13 from "../public/13.png";
import photo14 from "../public/14.png";
import photo15 from "../public/15.png";
import photo16 from "../public/16.png";
import photo17 from "../public/17.png";
import { MdWork } from "react-icons/md";

import i2 from "../public/i2.png";
import i3 from "../public/i3.png";
import i4 from "../public/i4.png";
import i5 from "../public/i5.png";
import i6 from "../public/i6.png";
import i7 from "../public/i7.png";
import i8 from "../public/i8.png";
import i9 from "../public/i9.png";
import i10 from "../public/i10.jpg";
import i11 from "../public/i11.png";
import i12 from "../public/i12.png";
import i13 from "../public/i13.png";
import i14 from "../public/i14.png";
import i15 from "../public/i15.png";
import i16 from "../public/i16.png";
import i17 from "../public/i17.webp";
import i18 from "../public/i18.png";
import i19 from "../public/i19.png";
import i20 from "../public/i20.png";
import i21 from "../public/i21.png";
import i22 from "../public/i22.png";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const options = {
      strings: ["Designer", "ICT Teacher", "Developer", "IT Support"],
      typeSpeed: 100,
      backSpeed: 80,
      backDelay: 2000,
      loop: true,
    };

    const typed = new Typed(".typedText", options);

    return () => {
      // Destroy Typed instance during cleanup to prevent memory leaks
      typed.destroy();
    };
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>SanVertPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://sanvert.vercel.app/images/home.jpg" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <h1></h1>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl text-gray-800 font-bold dark:text-white"> SAN VERT </h1>

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white text-gray-800"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="/sanvert.pdf" target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              San Vert
            </h2>
            <p className=" py-2 text-gray-800 dark:text-gray-200 md:text-4xl">
              I'm <span className="typedText text-teal-500 font-bold"></span>
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">
              Free Providing services for programming and design content and
              needs. Join me down below and let's get cracking!
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
          <a href="https://web.facebook.com/sanvertit/" target="_blank" ><AiFillFacebook /></a>
          <a href="https://github.com/itsanvert" target="_blank" ><AiFillGithub /></a>
          <a href="https://t.me/itsanvert" target="_blank" ><FaTelegram /></a>

          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 shadow-lg shadow-teal-500">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-bold text-gray-800">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and
              collaborated with talented people to create digital products for
              both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services, including brand design,
              programming, and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg shadow-teal-500 p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image src={design} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg shadow-teal-500 p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image src={code} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
            <div className="text-center shadow-lg shadow-teal-500 p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex justify-center">
                <Image src={consulting} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Consulting Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-gray-800 font-bold">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for{" "}
              <span className="text-teal-500">startups</span> and
              collaborated with talented people to create digital products for
              both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services, including brand design,
              programming, and teaching.
            </p>
            <h3 className="text-3xl text-gray-800 py-1 dark:text-white font-bold">Graphic Designed </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            
            <div className="basis-1/3 flex-1">
              <Image
                src={photo1}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                shadow
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo2}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo3}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo4}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo5}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo6}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo7}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo8}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div><div className="basis-1/3 flex-1">
              <Image
                src={photo9}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            
            <div className="basis-1/3 flex-1">
              <Image
                src={photo13}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo14}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo15}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo16}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={photo17}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className="text-3xl text-gray-800 py-10 dark:text-white font-bold">Finished Project Web Development </h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            
            <div className="basis-1/3 flex-1">
              <a href="http://vert-portfolio.vercel.app">
              <Image
                src={web1}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://itsanvert.github.io/Project01-Ecommerce-Website/">
              <Image
                src={web2}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://itsanvert.github.io/Project02-Build-University-Website/">
              <Image
                src={web3}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://itsanvert.github.io/Project04-SBKU-Website-clone/">
              <Image
                src={web4}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://itsanvert.github.io/Project05-SBKU-Bootstrap/">
              <Image
                src={web5}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://itsanvert.github.io/Project06-Travel-Website/">
              <Image
                src={web6}
                className="rounded-lg object-cover shadow-lg shadow-teal-500"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              </a>
            </div>
          </div>
          <section>
          <h3 className="text-3xl py-10 dark:text-white text-gray-800 font-bold ">Represent By</h3>
          <div className="sliderContainer " >
      <div className="logoSlider space-x-5 ">
        <img src="https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/apple-logo.png" alt="Apple Logo" />
        <img src="https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/google-logo.png" alt="Google Logo" />
        <img src="https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/microsoft-logo.png" alt="Microsoft Logo" />
        <img src="https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/samsung-logo.png" alt="Samsung Logo" />
        
        <Image src={i2} width={100} height={100} />
        <Image src={i3} width={100} height={100} />
        <Image src={i4} width={100} height={100} />
        <Image src={i5} width={100} height={100} />
        <Image src={i6} width={100} height={100} />
        <Image src={i7} width={100} height={100} />
        <Image src={i8} width={100} height={100} />
        <Image src={i9} width={100} height={100} />
        <Image src={i10} width={100} height={100} />
        <Image src={i11} width={100} height={100} />
        <Image src={i12} width={100} height={100} />
        <Image src={i13} width={100} height={100} />
        <Image src={i14} width={100} height={100} />
        <Image src={i15} width={100} height={100} />
        <Image src={i16} width={100} height={100} />
        <Image src={i17} width={100} height={100} />
        <Image src={i18} width={100} height={100} />
        <Image src={i19} width={100} height={100} />
        <Image src={i20} width={100} height={100} />
        <Image src={i21} width={100} height={100} />
        <Image src={i22} width={100} height={100} />

      </div>
    </div>
          </section>
          </div>
          <p className="text-xl font-bold text-center text-gray-800 py-10 dark:text-teal-500">@ 2024 | San Vert</p>
        </section>
      </main>
    </div>
  );
}
